### ISSUE TITLE
Marquee - Change sizing of headline when (1024px > window width > 720px) to 36px

### ISSUE THREAD

**Issue by codeswan** [grommet/hpe-digitaltoolkit#63]
Overrides part of issue #60

**Comment by mdctenga** [comment]
Context:

#60 says that the Headline font-size should be 48 px for middle size browser widths (From 1023 to 720 px), but this ticket overrides that ticket and say the font-size should be 36 px.

Issue:

- Headline font-size is 48 px at a browser width of 720 px

![Font-size is 48px instead of 36px](https://cloud.githubusercontent.com/assets/8364525/16167315/298d6934-348f-11e6-9716-d281fe91b3c3.png)

**Comment by codeswan** [comment]
This has been fixed, the font-size is now 36px for middle-size browser widths.
