### ISSUE TITLE
Section Component

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-digitaltoolkit#95]

**Comment by prewalia** [comment]
Hey :) here is the Section Accolade at designs. I've broken each design into different break point started from 1440 px to mobile and have also specified the type for the same. Please let me know if you want more information on anything! :) 

**OPTION 1:** Image with a colored box on top with copy in it. We thought this option could be used when we come across images that don’t support copy that well, so instead of editing the image or adding a shadow we could probably use this option. 

**OPTION 2:** This is the very basic one, with image and copy on top of it (Versions: copy left, copy right, copy centered on a normal image and one with a color overlay)

[SectionDesign_Accolade_FINAL.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/376874/SectionDesign_Accolade_FINAL.pdf)

Here is the InVision link for the same: https://invis.io/2B81DY5UP

Let me know if you have any questions!

Thanks,
Pre

**Comment by kyle-locke** [comment]
[component-anatomy-section.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/382711/component-anatomy-section.pdf)

**Comment by kyle-locke** [comment]
Section files are being updated based on yesterdays discussion. Sorry for the delay.

**Comment by prewalia** [comment]
Hey guys here are the final section designs with and w/o the grid. So in each breakpoint 1440, 960 and 768 the content is taking unto 50% of the column grid width. We have a grid of 12 columns with 24 px gutter throughout. As you can see in each design of different break points the content is taking up to 6 columns out of 12 so 50%

In simple words the **text box**  **=** **width of 6 columns** and is inside of a box which has 48 px padding all around from the text box. Does that make sense?

Box and content **specification:**
[SectionDesign_Accolade_Specifications..pdf](https://github.com/grommet/hpe-digitaltoolkit/files/385295/SectionDesign_Accolade_Specifications.pdf)

**Design with grid:**
[SectionDesign_Accolade_With_The_Grid.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/385296/SectionDesign_Accolade_With_The_Grid.pdf)


**Design without grid:**
[SectionDesign_Accolade_Without_Grid.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/385297/SectionDesign_Accolade_Without_Grid.pdf)

**Comment by prewalia** [comment]
And here is the InVision link: https://invis.io/XK80SU2CA

**Comment by kyle-locke** [comment]
Wiki has been updated:
https://github.com/grommet/hpe-digitaltoolkit-design/wiki
